plugin: aws_ec2
regions:
  - us-east-1
filters:
  instance-state-name: running
  tag:Role: prometheus
keyed_groups:
  - key: tags.Name
    prefix: instance
hostnames:
  - public-ip-address
compose:
  ansible_host: public-ip-address
